# Generated by Django 4.1.1 on 2022-10-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libreria', '0006_rename_id_estudiante_id_estudiante'),
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='promedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('nota3', models.FloatField()),
                ('promedio', models.FloatField()),
                ('id_estudiante1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.estudiante')),
                ('id_materia1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaturas.materia')),
            ],
        ),
    ]
