# Generated by Django 4.1.1 on 2022-09-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('materias', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='promedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('id_estudiante1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.estudiante')),
                ('id_materia1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.materia')),
            ],
        ),
    ]
