# Generated by Django 4.1.1 on 2022-09-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promedio',
            old_name='promedio',
            new_name='nota1',
        ),
        migrations.AddField(
            model_name='promedio',
            name='nota2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promedio',
            name='nota3',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
