# Generated by Django 4.1.1 on 2022-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_promedio_promedio_nota1_promedio_nota2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promedio',
            name='promedio',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
