# Generated by Django 4.1.1 on 2022-09-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_promedio_promedio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='id_estudiante',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='id_materia',
            new_name='id',
        ),
    ]
