# Generated by Django 4.1.1 on 2022-10-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_id_estudiante_estudiante_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promedio',
            name='id_estudiante1',
        ),
        migrations.RemoveField(
            model_name='promedio',
            name='id_materia1',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='promedio',
        ),
    ]
