# Generated by Django 4.1.1 on 2022-10-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_remove_promedio_id_estudiante1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='id',
            new_name='id_estudiante',
        ),
    ]
